// Generated by CoffeeScript 1.4.0
(function() {
  var SpaceShip, THREE, spaceLib;

  THREE = require('../lib/THREEMath.js').THREE;

  SpaceShip = (function() {

    function SpaceShip() {
      this.matrix = new THREE.Matrix4();
    }

    return SpaceShip;

  })();

  spaceLib = require("../lib/space.js");

  exports['create space ship'] = function(test) {
    var ship, space;
    space = new spaceLib.Space();
    ship = space.addObject(new SpaceShip());
    return test.done();
  };

}).call(this);
