// Generated by CoffeeScript 1.4.0
(function() {
  var JsonDiff;

  JsonDiff = (function() {

    function JsonDiff() {}

    JsonDiff.prototype.merge = function(oA, oB) {
      var item, k, self, _i, _j, _len, _len1, _ref, _ref1;
      self = this;
      if (typeof oB === "object") {
        if (oB.__isArray === void 0) {
          _ref = Object.keys(oB);
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            k = _ref[_i];
            oA[k] = self.merge(oA[k], oB[k]);
          }
          return oA;
        } else {
          _ref1 = oB.__updates;
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            item = _ref1[_j];
            oA[item.k] = self.merge(oA[item.k], item.v);
          }
          return oA;
        }
      } else {
        return oB;
      }
    };

    JsonDiff.prototype.getDelta = function(oA, oB) {
      var delta, self;
      self = this;
      delta = void 0;
      if (oA === void 0) {
        delta = oB;
      } else if (typeof oB === "object") {
        if (Array.isArray(oB)) {
          if (oB.length !== oA.length) {
            return delta = oB;
          }
          Object.keys(oB).forEach(function(key) {
            var d;
            d = self.getDelta(oA[key], oB[key]);
            if (d !== void 0) {
              if (delta === void 0) {
                delta = new Object();
                delta.__isArray = true;
                delta.__updates = [];
              }
              return delta.__updates.push({
                k: key,
                v: d
              });
            }
          });
        } else {
          Object.keys(oB).forEach(function(key) {
            var d;
            d = self.getDelta(oA[key], oB[key]);
            if (d !== void 0) {
              if (delta === void 0) {
                delta = new Object();
              }
              return delta[key] = d;
            }
          });
        }
      } else if (oA !== oB) {
        delta = oB;
      }
      return delta;
    };

    return JsonDiff;

  })();

  exports.JsonDiff = JsonDiff;

}).call(this);
