// Generated by CoffeeScript 1.4.0
(function() {
  var Lobby, userlib;

  userlib = require("../lib/user.js");

  Lobby = (function() {

    function Lobby() {}

    Lobby.prototype.users = [];

    Lobby.prototype.i = 0;

    Lobby.prototype.createUser = function(stream) {
      var u;
      u = new userlib.User("user_" + this.i, this, stream);
      this.users.push(u);
      this.i += 1;
      return u;
    };

    Lobby.prototype.remove = function(user) {
      return this.users.splice(this.users.indexOf(user), 1);
    };

    return Lobby;

  })();

  exports.Lobby = Lobby;

}).call(this);
