// Generated by CoffeeScript 1.4.0
(function() {
  var Space;

  Space = (function() {

    function Space() {
      this.objects = [];
    }

    Space.prototype.addObject = function(p) {
      return this.objects.push(p);
    };

    Space.prototype.update = function(pDeltaTime) {
      var o, _i, _len, _ref, _results;
      _ref = this.objects;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        o = _ref[_i];
        if (o.update !== void 0) {
          _results.push(o.update(pDeltaTime));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    return Space;

  })();

  exports.Space = Space;

}).call(this);
