// Generated by CoffeeScript 1.4.0
(function() {
  var User;

  User = (function() {

    User.prototype.parseMessage = function(m) {
      if (m.credentials !== void 0) {
        return this.credentials = m.credentials;
      } else {
        return console.log("got unhandled message of type " + m.type);
      }
    };

    User.prototype.quit = function(data) {
      return this.lobby.remove(this);
    };

    function User(name, lobby, stream) {
      var self;
      this.lobby = lobby;
      this.stream = stream;
      self = this;
      this.credentials = {
        name: name
      };
      this.stream.on('json', function(data) {
        return self.parseMessage(data);
      });
      this.stream.on('disconnect', function() {
        return self.quit();
      });
    }

    return User;

  })();

  exports.User = User;

}).call(this);
